HttpListen:
  Ip: 0.0.0.0
  Port: 8005

Logs:
  PathToLogFile: logs/all.log
  Level: debug

DB:
  Host: 127.0.0.1
  Port: 5433
  Dbname: postgres
  PoolMaxConns: 15
  Password: postgres
  User: postgres