test:
	go test ./... -cover

migrate:
	migrate create -ext sql -dir app/infrastructure/migrations -seq $(comment)

upgrade_db:
	migrate -path app/infrastructure/migrations -database postgres://postgres:postgres@localhost:5433/postgres?sslmode=disable up


down_to:
	migrate -path app/infrastructure/migrations -database postgres://postgres:postgres@localhost:5433/postgres?sslmode=disable down $(rev)

force:
	migrate -path app/infrastructure/migrations -database postgres://postgres:postgres@localhost:5433/postgres?sslmode=disable force $(ver)
